apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdflayout-api-deployment
  namespace: dpc-pdfgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdflayout-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pdflayout-api
    spec:
      containers:
      - image: spbdocker03:5000/dpc-pdfgenerator/pdflayout-api:||version||
        name: pdflayout-api        
        ports:
        - containerPort: 80
        resources: 
          limits:
            memory: "256Mi"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 30   
---
apiVersion: v1
kind: Service
metadata:
  name: pdflayout-api-service
  namespace: dpc-pdfgenerator
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: reporting-api
