apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdflayout-pv
  namespace: dpc-pdfgenerator
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/msckubepv/dpc-pdflayout
    server: 172.16.4.200
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pdflayout-pvc
  namespace: dpc-pdfgenerator
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pdflayout-pv
  resources:
    requests:
      storage: 100Mi
